In [1]:
import numpy as np
import pandas as pd

In [10]:
# Create a NumPy array with values [1, 2, 3, 4, 5] 
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [11]:
# and multiply every element by 2.
a*2

array([ 2,  4,  6,  8, 10])

In [17]:
# Generate a 3x3 identity matrix.
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Create an array of 10 zeros
c=np.zeros(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# and an array of 10 ones.
d=np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# Create an array of evenly spaced numbers between 0 and 50 
# with a step size of 5.
e=np.arange(0,51,5)
e

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
# Extract all even numbers from a given array [1, 2, 3, 4, 5, 6, 7, 8].
f=np.array([1,2,3,4,5,6,7,8])
even_num=[i for i in f if i%2==0]
print(even_num)

[2, 4, 6, 8]


In [30]:
# Create a 5x5 array with random values and extract the first two rows.
g=np.random.rand(5,5)
print(g)

[[0.81535043 0.75992545 0.02087972 0.24261272 0.23903589]
 [0.54187635 0.33433959 0.46488081 0.29341079 0.25396817]
 [0.14939505 0.35294772 0.55275743 0.81205502 0.093172  ]
 [0.4275143  0.98885126 0.66869093 0.85001705 0.2632065 ]
 [0.06178373 0.12637977 0.34173147 0.71673863 0.2995    ]]


In [39]:
# Create a 1D array and reverse its elements.
h=np.array([1,2,3,4,5,6,7,8,9,10])
h=h[::-1]
print(h)

[10  9  8  7  6  5  4  3  2  1]


In [89]:
# Perform element-wise addition, subtraction, multiplication, and 
# division on two arrays
# The error occurs because Python lists do not support
# element-wise arithmetic operations,
# but NumPy arrays do.
arr1=np.array([10,20,30])
arr2=np.array([1,2,3])
print(f'array 1 : {arr1}')
print(f'array 2 : {arr2}')
add=arr1+arr2
sub=arr1-arr2
mult=arr1*arr2
div=arr1/arr2
print(f'add : {add}')
print(f'sub : {sub}')
print(f'mult : {mult}')
print(f'div : {div}')

array 1 : [10 20 30]
array 2 : [1 2 3]
add : [11 22 33]
sub : [ 9 18 27]
mult : [10 40 90]
div : [10. 10. 10.]


In [48]:
# Compute the square root and exponential of the array.
i=np.array([1,4,9,16,25])
arr1=np.sqrt(i)
arr2=np.exp(i)
print(i)
print(arr1)
print(arr2)

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [52]:
j=np.array([10,20,30,40,50])
mean=np.mean(j)
median=np.median(j)
std_dev=np.std(j)
variance=np.var(j)
print(j)
print(mean)
print(median)
print(std_dev)
print(variance)

[10 20 30 40 50]
30.0
30.0
14.142135623730951
200.0


In [54]:
# Find the maximum and minimum values and their indices in the array.
k=np.array([7,1,3,10,5])
min1=np.min(k)
max1=np.max(k)
print(k)
print(min1)
print(max1)

[ 7  1  3 10  5]
1
10


In [57]:
# Reshape a 1D array [1, 2, 3, 4, 5, 6] into a 2x3 matrix.
l=np.array([1,2,3,4,5,6])
arr1=l.reshape(2,3)
print(l)
print(arr1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [58]:
# Create a 4x4 array and transpose it.
m=np.random.randint(1,10,(4,4))
arr1=m.T
print(m)
print(arr1)

[[9 6 2 6]
 [6 2 3 5]
 [2 9 6 5]
 [8 8 1 5]]
[[9 6 2 8]
 [6 2 9 8]
 [2 3 6 1]
 [6 5 5 5]]


In [60]:
# Add a 1D array [1, 2, 3] to every row of a 3x3 matrix.
n=np.array(([4,5,6],[7,8,9],[10,11,12]))
o=np.array([1,2,3])
result=n+o
print(n)
print(o)
print(result)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]
[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [61]:
# Subtract the mean of each column from the elements of a 2D array.
p=np.array(([[1, 2, 3],[4, 5, 6],[7, 8, 9]])) 
arr1=np.mean(p,axis=0)
result=p-arr1
print(p)
print(arr1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [62]:
# Create an array [5, 10, 15, 20, 25] and find elements greater than 15.
q=np.array([5,10,15,20,25])
result=[i for i in q if i>15]
print(q)
print(result)

[ 5 10 15 20 25]
[20, 25]


In [65]:
# Replace all negative values in the array [-1, -2, 3, 4] with 0.
r=np.array([-1,-2,-3,4])
r[r<0]=0
print(r)

[0 0 0 4]


In [66]:
# Create a diagonal matrix with diagonal values [10, 20, 30].
s=np.diag([10,20,30])
s

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [69]:
# Create a 3D array of shape (2, 3, 4) with random integers.
t=np.random.randint(0,10,(2,3,4))
print(t)

[[[4 0 8 8]
  [2 5 5 5]
  [5 9 1 0]]

 [[8 3 2 4]
  [3 8 5 8]
  [1 2 1 8]]]


In [77]:
# Use fancy indexing to extract values [20, 40] from the array 
# [10, 20, 30, 40, 50].
u=np.array([10,20,30,40,50])
print(u[1],u[3])

20 40


In [83]:
# Sum all elements in a 2D array and compute the sum along rows and columns.
v=np.array(([1,2],[3,4],[5,6],[7,8],[9,10]))
sum1=np.sum(v)
sum2=np.sum(v,axis=1)
sum3=np.sum(v,axis=0)
print(v)
print('sum1',sum1)
print('sum2',sum2)
print('sum3',sum3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
sum1 55
sum2 [ 3  7 11 15 19]
sum3 [25 30]


In [85]:
# Compute the cumulative sum of the array [1, 2, 3, 4].
w=np.array([1,2,3,4])
w.cumsum()

array([ 1,  3,  6, 10])

In [86]:
# Generate an array of 5 random integers between 1 and 100.
x=np.random.randint(1,100,5)
x

array([14, 56, 14, 71, 48])

In [88]:
# Create a 2D array with random floats between 0 and 1.
y=np.random.rand(3,4)
y

array([[0.38889911, 0.4602667 , 0.4023966 , 0.32920368],
       [0.1389537 , 0.04330976, 0.89505651, 0.40743314],
       [0.44715023, 0.13381201, 0.14172458, 0.99664506]])