In [1]:
import numpy as np

In [6]:
a=[]
size=int(input("enter your value: "))
for i in range(size):
  var=input("enter your item: ")
  a.append(var)
b=np.array(a)
print (b)

enter your value: 3
enter your item: sam
enter your item: max
enter your item: shiv
['sam' 'max' 'shiv']


In [13]:
a=np.array([1,2,3,4,5])
a.shape
a.size

5

In [15]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [17]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
a=np.random.randint(1,5,3)
a

array([4, 3, 3])

In [28]:
a=np.random.randint(1,5,3)
a.shape
a.reshape(1,3)

array([[4, 3, 3]])

In [34]:
a=np.array([6,2,3,4,5])
b=a.view()
a[0]=1
print (a)
print (b)

[1 2 3 4 5]
[1 2 3 4 5]


In [42]:
a=np.arange(1,6)
print (a)
print (a+3)

[1 2 3 4 5]
[4 5 6 7 8]


In [45]:
a=np.array([1,2,3,4,5])
a.min()
a.max()
a.argmin()

0

In [51]:
import numpy as np

In [46]:
arr=np.array([1,2,3,4,5])
print (arr)

[1 2 3 4 5]


In [47]:
a=np.random.randint(1,5,3)
print (a)

[1 3 1]


In [50]:
a=np.arange(10,21)
print (a)

[10 11 12 13 14 15 16 17 18 19 20]


In [55]:
a=np.ones(10) * 5
print (a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [58]:
a=np.array([1,2,3,4,5,6,7,8,9])
print (a.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
a=np.random.rand(9)
print (a.reshape(9))

[0.58203764 0.08443282 0.08468249 0.45080182 0.14108119 0.12841316
 0.01690996 0.4562681  0.22355175]


In [77]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print ("vertically: \n",a)
print ("horizantally: \n",a.reshape(9))

vertically: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
horizantally: 
 [1 2 3 4 5 6 7 8 9]
