In [1]:
import numpy as np

In [2]:
# checking numpy version
np.__version__

'1.26.4'

In [3]:
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.
arr=np.array([1,2,3,4,5])
print (type(arr)),print (arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


(None, None)

In [4]:
# dimensions in arrays
# 0-D ARRAYS
# 0-D arrays, or Scalars, are the elements in an array.
# Each value in an array is a 0-D array.
arr=np.array(40)
print (arr)

40


In [5]:
# 1-D ARRAYS
# an array that has 0-D array as its elements is uni-dimensional
# or 1-D array , these are the most common and basic arrays
arr=np.array([1,2,4,6,8])
print (arr)

[1 2 4 6 8]


In [6]:
# 2-D ARRAY
# AN ARRAY THAT HAS 1-D ARRAY AS ITS ELEMENTS IS 2-D ARRAY
# THESE ARE OFTEN USED TO REPRESENT MATRIX OR 2ND ORDER TENSORS
arr=np.array([[1,3,5],[2,4,6]])
print (arr)

[[1 3 5]
 [2 4 6]]


In [7]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements 
# called 3-D array.
# These are often used to represent a 3rd order tensor.
arr=np.array([[[1,3,5],[7,9,11]],[[2,4,6],[8,10,12]]])
arr

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

In [8]:
# Check Number of Dimensions?
# NumPy Arrays provides the 'ndim' attribute that 
# returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.
# When the array is created
# you can define the number of dimensions by using the ndmin argument.
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
# numpy array indexing
a=np.array([1,2,3,4,5])
print (a[2] + a[3])

7


In [11]:
# numpy array slicing
a=np.array([1,2,3,4,5,6,7,8,9,10])
print (a[::2])

[1 3 5 7 9]


In [12]:
# numpy data types
a=np.array([1,2,3,4,5])
print(a.dtype)

int32


In [13]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [14]:
a=np.array([1.1,2.2,2.3])
b=a.astype('i')
print (b)
print (b.dtype)

[1 2 2]
int32


In [15]:
a=np.array([1,1,0])
b=a.astype(bool)
print (b)
print (b.dtype)

[ True  True False]
bool


In [16]:
# numpy array copy vs view
a=np.array([1,2,3,4,5])
b=a.copy()
a[0]=42
print (a)
print (b)

[42  2  3  4  5]
[1 2 3 4 5]


In [17]:
a=np.array([1,2,3,4,5])
b=a.view()
a[0]=42
print (a)
print (b)

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
n1=np.array([2,2,3,4,5])
m1=n1.view()
n1[0]=1
print (n1)
print (m1)

[1 2 3 4 5]
[1 2 3 4 5]


In [19]:
# check if array owns the data?
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]
